name: Payment Deployment
on: [push, workflow_dispatch]
jobs:
  deploy:
    uses: VenkatBheemireddyOrg/github-reusable-actions/.github/workflows/deploy.yml@main
    with:
      component: payment     #with block is to pass parameter

